Repository mosecorg/mosec, pull requests merged in 2023-04, with the labels that each got.

#322 feat: use axum instead of pure hyper
  Cargo.lock
  Cargo.toml
  src/main.rs
  tests/bad_req.py
Labels: enhancement

#321 feat: Set timeout for worker.forward
  mosec/coordinator.py
  mosec/errors.py
  mosec/protocol.py
  mosec/server.py
  src/main.rs
  src/protocol.rs
  src/tasks.rs
  tests/test_coordinator.py
  tests/test_timeout_service.py
  tests/timeout_service.py
Labels: enhancement

#323 fix: avoid timeout test failing and orphan service in CI
  Cargo.lock
  Cargo.toml
  examples/jax_single_layer_cli.py
  examples/resnet50_client_msgpack.py
  examples/stable_diffusion/client.py
  mosec/coordinator.py
  tests/bad_req.py
  tests/test_service.py
  tests/test_timeout_service.py
  tests/timeout_service.py
  tests/utils.py
Labels: bug_fix

#334 docs: rm the outdated comparison
  README.md
Labels: documentation

#336 chore: Update adopters
  README.md
Labels: chore

#337 chore: add image
  README.md
Labels: chore

#335 refactor: switch to official prometheus client
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/metrics.rs
  src/protocol.rs
Labels: refactoring
