Repository mosecorg/mosec, pull requests merged in 2023-03, with the labels that each got.

#292 feat: Add adopters
  README.md
Labels: enhancement

#290 docs: fix links and rearrange readme
  README.md
  examples/README.md
Labels: documentation

#293 docs: add CI links checker
  .github/workflows/links.yml
  CONTRIBUTING.md
  README.md
  docs/source/conf.py
Labels: documentation

#294 docs: minor fix on README.md
  README.md
Labels: documentation

#295 feat: enable configuring wait time for different stages
  mosec/args.py
  mosec/server.py
  mosec/worker.py
  src/args.rs
  src/coordinator.rs
Labels: enhancement

#299 feat: support dry run the service
  examples/echo.py
  mosec/args.py
  mosec/dry_run.py
  mosec/env.py
  mosec/server.py
Labels: enhancement

#301 feat: support set up the arguments through environment variables
  Cargo.lock
  Cargo.toml
  README.md
  examples/stable_diffusion/server.py
  mosec/args.py
  mosec/env.py
Labels: enhancement

#304 feat: add metric for dynamic batching duration
  README.md
  mosec/args.py
  src/metrics.rs
  src/protocol.rs
Labels: enhancement

#305 feat: add numbin as an IPC mixin
  .github/workflows/check.yml
  .github/workflows/package.yml
  Makefile
  mosec/mixin/__init__.py
  mosec/mixin/numbin_worker.py
  requirements/dev.txt
  requirements/plugin.txt
  tests/mixin_numbin_service.py
  tests/test_coordinator.py
  tests/test_service.py
Labels: enhancement

#306 feat: add py.typed file
  Cargo.lock
  Cargo.toml
  MANIFEST.in
  mosec/py.typed
Labels: enhancement

#308 fix: align warmup example format in dry run
  examples/echo.py
  mosec/dry_run.py
Labels: bug_fix

#310 fix: wait all the worker init done in dry run
  Cargo.lock
  Cargo.toml
  mosec/dry_run.py
Labels: bug_fix

#311 fix: resolve deadlock when lots of client requests closed before response
  Cargo.lock
  Cargo.toml
  mosec/server.py
  src/tasks.rs
Labels: bug_fix

#312 chore: skip the lint&test step in release
  .github/workflows/package.yml
Labels: chore

#313 chore: add nightly bad req test
  .github/workflows/nightly.yml
  .github/workflows/page.yml
  tests/bad_req.py
Labels: chore

#314 chore: use absolute import path
  mosec/__init__.py
  mosec/args.py
  mosec/coordinator.py
  mosec/dry_run.py
  mosec/errors.py
  mosec/log.py
  mosec/mixin/__init__.py
  mosec/mixin/msgpack_worker.py
  mosec/mixin/numbin_worker.py
  mosec/plugins/__init__.py
  mosec/plugins/plasma_shm.py
  mosec/protocol.py
  mosec/server.py
  mosec/worker.py
  tests/test_coordinator.py
  tests/test_protocol.py
  tests/utils.py
Labels: chore

#316 fix: hold one lock at a time to avoid the deadlock in nested function
  Cargo.lock
  Cargo.toml
  src/tasks.rs
  tests/bad_req.py
  tests/bad_service.py
Labels: bug_fix

#315 feat: change parking lot mutex to std mutex
  Cargo.lock
  Cargo.toml
  src/tasks.rs
Labels: enhancement
