Repository mosecorg/mosec, pull requests merged in 2023-06, with the labels that each got.

#374 feat: support dynamic inference route
  mosec/dry_run.py
  mosec/env.py
  mosec/manager.py
  mosec/server.py
  src/args.rs
  src/main.rs
  src/protocol.rs
  tests/square_service.py
  tests/test_coordinator.py
  tests/test_service.py
Labels: enhancement

#378 docs: mark ipc wrapper as deprecated
  Cargo.lock
  Cargo.toml
  docs/source/examples/ipc.md
  license.json
  mosec/ipc.py
  mosec/plugins/plasma_shm.py
  mosec/server.py
Labels: documentation

#379 fix: check child process exit code
  Cargo.lock
  Cargo.toml
  license.json
  mosec/manager.py
Labels: bug_fix

#380 chore: add sleep to service test to catch the check bug
  tests/test_service.py
Labels: chore

#370 feat: provide openapi doc
  Cargo.lock
  Cargo.toml
  examples/jax_single_layer.py
  examples/type_validation/server.py
  mosec/mixin/typed_worker.py
  mosec/server.py
  mosec/utils/__init__.py
  mosec/utils/types.py
  mosec/worker.py
  src/apidoc.rs
  src/main.rs
  tests/openapi_service.py
  tests/test_service.py
  tests/test_utils.py
Labels: enhancement

#333 feat: support server sent event
  Cargo.lock
  Cargo.toml
  examples/server_side_event/client.py
  examples/server_side_event/server.py
  mosec/coordinator.py
  mosec/errors.py
  mosec/protocol.py
  mosec/worker.py
  pyproject.toml
  requirements/dev.txt
  rustfmt.toml
  src/apidoc.rs
  src/errors.rs
  src/main.rs
  src/protocol.rs
  src/routes.rs
  src/tasks.rs
  tests/sse_service.py
  tests/test_service.py
Labels: enhancement

#391 refactor: sse abstraction in worker and coordinator
  .github/workflows/check.yml
  examples/server_side_event/server.py
  mosec/__init__.py
  mosec/coordinator.py
  mosec/dry_run.py
  mosec/runtime.py
  mosec/server.py
  mosec/worker.py
  src/main.rs
  tests/sse_service.py
  tests/test_coordinator.py
Labels: refactoring

#394 feat: support `--log-level` CLI argument
  .github/workflows/nightly.yml
  Cargo.lock
  Cargo.toml
  mosec/args.py
  mosec/env.py
  mosec/log.py
  mosec/runtime.py
  src/args.rs
  src/main.rs
  tests/bad_req.py
  tests/services/__init__.py
  tests/services/bad_service.py
  tests/services/mixin_ipc_shm_service.py
  tests/services/mixin_numbin_service.py
  tests/services/mixin_typed_service.py
  tests/services/openapi_service.py
  tests/services/square_service.py
  tests/services/sse_service.py
  tests/services/timeout_service.py
  tests/test_coordinator.py
  tests/test_log.py
  tests/test_service.py
  tests/test_timeout_service.py
  tests/utils.py
Labels: enhancement

#396 chore: add readthedoc support
  .readthedocs.yaml
  Makefile
  docs/source/index.md
Labels: chore

#399 chore: align the naming, fix the test lint
  Makefile
  examples/jax_single_layer_cli.py
  examples/resnet50_client_msgpack.py
  examples/stable_diffusion/client.py
  mosec/args.py
  mosec/dry_run.py
  mosec/mixin/plasma_worker.py
  mosec/runtime.py
  mosec/server.py
  pyproject.toml
  setup.py
  tests/bad_req.py
  tests/mock_socket.py
  tests/services/bad_service.py
  tests/services/mixin_ipc_shm_service.py
  tests/services/mixin_numbin_service.py
  tests/services/mixin_typed_service.py
  tests/services/openapi_service.py
  tests/services/square_service.py
  tests/services/sse_service.py
  tests/services/timeout_service.py
  tests/test_coordinator.py
  tests/test_log.py
  tests/test_protocol.py
  tests/test_service.py
  tests/test_utils.py
  tests/utils.py
Labels: chore

#400 docs: update readme about pid 1 and dynamic batching
  README.md
Labels: documentation

#401 docs: fix readthedocs build config
  .readthedocs.yaml
Labels: documentation
