Repository mosecorg/mosec, pull requests merged in 2023-02, with the labels that each got.

#263 feat: warning for the IPC data size
  examples/plasma_shm_ipc.py
  mosec/protocol.py
Labels: enhancement

#268 fix: only parse known arguments
  Cargo.lock
  Cargo.toml
  mosec/args.py
Labels: bug_fix

#269 fix: delete the task if the notifier channel is closed
  Cargo.lock
  Cargo.toml
  mosec/server.py
  src/tasks.rs
Labels: bug_fix

#270 fix: ignore the rmtree error
  mosec/server.py
Labels: bug_fix

#271 fix: warn about the timeout and channel is full
  Cargo.lock
  Cargo.toml
  src/tasks.rs
Labels: bug_fix

#272 fix: return equal number of error payloads
  Cargo.lock
  Cargo.toml
  examples/echo.py
  mosec/coordinator.py
Labels: bug_fix

#279 feat: support colorful log for debug and json log for production
  Cargo.lock
  Cargo.toml
  README.md
  examples/custom_env.py
  examples/distil_bert_server_pytorch.py
  examples/echo.py
  examples/jax_single_layer.py
  examples/plasma_shm_ipc.py
  examples/python_side_metrics.py
  examples/resnet50_server_msgpack.py
  examples/stable_diffusion/server.py
  mosec/__init__.py
  mosec/args.py
  mosec/coordinator.py
  mosec/log.py
  mosec/plugins/plasma_shm.py
  mosec/protocol.py
  mosec/server.py
  mosec/worker.py
  src/args.rs
  src/main.rs
  tests/test_coordinator.py
  tests/test_service.py
Labels: enhancement

#280 docs: add templates for issue and feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/workflows/check.yml
Labels: documentation

#282 docs: use stable diffusion as an example in the readme
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  examples/stable_diffusion/client.py
Labels: documentation

#283 feat: improve the log msg to make it more friendly
  examples/custom_env.py
  examples/echo.py
  mosec/coordinator.py
  mosec/server.py
  src/coordinator.rs
  src/main.rs
  src/protocol.rs
  src/tasks.rs
Labels: enhancement

#284 docs: add config suggestion and deployment tutorial
  README.md
Labels: documentation

#285 docs: fix typo in readme
  Cargo.lock
  Cargo.toml
  README.md
Labels: documentation

#287 docs: refine readme and example codes
  README.md
  examples/stable_diffusion/server.py
  mkdocs.yml
Labels: documentation

#288 docs: change to sphinx docs
  .github/workflows/page.yml
  CONTRIBUTING.md
  Makefile
  docs/Makefile
  docs/argument.md
  docs/contributing.md
  docs/design/index.md
  docs/example/stable_diffusion.md
  docs/index.md
  docs/interface.md
  docs/make.bat
  docs/source/conf.py
  docs/source/development/contributing.md
  docs/source/development/index.md
  docs/source/examples/echo.md
  docs/source/examples/env.md
  docs/source/examples/index.md
  docs/source/examples/ipc.md
  docs/source/examples/jax.md
  docs/source/examples/metric.md
  docs/source/examples/pytorch.md
  docs/source/examples/stable_diffusion.md
  docs/source/index.md
  docs/source/license.md
  docs/source/reference/arguments.md
  docs/source/reference/index.md
  docs/source/reference/interface.md
  docs/styles/extra.css
  mkdocs.yml
  mosec/errors.py
  mosec/ipc.py
  mosec/mixin/msgpack_worker.py
  mosec/plugins/plasma_shm.py
  mosec/server.py
  mosec/worker.py
  requirements/doc.txt
  scripts/gen_docs_args.py
Labels: documentation
