Repository mosecorg/mosec, pull requests merged in 2023-05, with the labels that each got.

#341 chore: add dependencies license file
  Cargo.lock
  Cargo.toml
  MANIFEST.in
  Makefile
  license.json
  mosec/mixin/msgpack_worker.py
  requirements/plugin.txt
Labels: chore

#346 chore: only enable nightly test for Linux
  .github/workflows/nightly.yml
Labels: chore

#354 docs: fix plasma related doc, add deprecate warning
  docs/source/examples/ipc.md
  docs/source/examples/pytorch.md
  mosec/mixin/plasma_worker.py
  mosec/plugins/plasma_shm.py
Labels: documentation

#356 chore: Add tencent cloud
  README.md
Labels: chore

#352 feat: support request validation according to annotation
  .github/workflows/check.yml
  .github/workflows/nightly.yml
  .github/workflows/page.yml
  .gitignore
  Makefile
  README.md
  docs/source/examples/index.md
  docs/source/examples/validate.md
  examples/stable_diffusion/client.py
  examples/type_validation/client.py
  examples/type_validation/server.py
  mosec/mixin/__init__.py
  mosec/mixin/typed_worker.py
  pyproject.toml
  requirements/dev.txt
  requirements/mixin.txt
  requirements/plugin.txt
  setup.py
  tests/mixin_typed_service.py
  tests/test_service.py
  tests/test_utils.py
Labels: enhancement

#358 docs: combine the metrics related page
  Cargo.lock
  Cargo.toml
  docs/source/examples/metric.md
  examples/monitor/README.md
  examples/python_side_metrics.py
Labels: documentation

#360 feat: add content type to the inference response header
  examples/distil_bert_server_pytorch.py
  mosec/mixin/msgpack_worker.py
  mosec/mixin/typed_worker.py
  mosec/server.py
  mosec/worker.py
  src/args.rs
  src/main.rs
  tests/test_service.py
Labels: enhancement

#368 fix: use try to import msgspec
  mosec/mixin/msgpack_worker.py
  mosec/mixin/typed_worker.py
Labels: bug_fix

#369 fix: plasma mixin should use super serde with shm storage
  examples/plasma_shm_ipc.py
  mosec/mixin/plasma_worker.py
  requirements/dev.txt
  tests/mixin_ipc_shm_service.py
  tests/test_service.py
Labels: bug_fix

#367 feat: support redis shm mixin
  .github/workflows/check.yml
  docs/source/examples/ipc.md
  examples/redis_shm_ipc.py
  mosec/mixin/__init__.py
  mosec/mixin/redis_worker.py
  requirements/mixin.txt
  tests/mixin_ipc_shm_service.py
  tests/test_service.py
Labels: enhancement

#371 fix: args should only be checked when server is used
  .github/workflows/check.yml
  Makefile
  build.envd
  mosec/args.py
  mosec/log.py
  mosec/server.py
  pyproject.toml
  tests/test_service.py
Labels: bug_fix
