Repository mosecorg/mosec, pull requests merged in 2023-01, with the labels that each got.

#253 fix: worker property
  Cargo.lock
  Cargo.toml
  Makefile
  mosec/coordinator.py
  mosec/worker.py
  tests/test_coordinator.py
Labels: bug_fix

#257 feat: add multi_example for warmup and add jax example
  README.md
  docs/example/jax.md
  docs/example/pytorch.md
  examples/jax_single_layer.py
  examples/jax_single_layer_cli.py
  mkdocs.yml
  mosec/coordinator.py
  mosec/worker.py
Labels: documentation, enhancement, python

#260 feat: add envd as a dev env tool
  Cargo.lock
  Cargo.toml
  README.md
  build.envd
  requirements/dev.txt
Labels: enhancement

#261 docs: add a stable diffusion serving example
  README.md
  docs/example/stable_diffusion.md
  examples/__init__.py
  examples/stable_diffusion/build.envd
  examples/stable_diffusion/client.py
  examples/stable_diffusion/server.py
  mkdocs.yml
  src/metrics.rs
Labels: documentation
