Repository mosecorg/mosec, pull requests merged in 2023-07, with the labels that each got.

#406 chore: add the codeql lint config
  .github/workflows/codeql.yml
  .readthedocs.yaml
Labels: chore

#407 feat: support swagger-ui for the openapi
  Cargo.lock
  Cargo.toml
  src/apidoc.rs
  src/main.rs
  src/routes.rs
  tests/test_service.py
Labels: enhancement

#409 docs: add performance tuning guide
  Makefile
  README.md
  docs/source/reference/interface.md
  examples/distil_bert_server_pytorch.py
  mosec/args.py
Labels: documentation

#411 docs: add concepts, faq, migration guide
  .github/workflows/links.yml
  .lycheeignore
  docs/Makefile
  docs/source/reference/concept.md
  docs/source/reference/index.md
  docs/source/reference/migration.md
  lychee.toml
  mosec/server.py
Labels: documentation

#412 chore: fix the sphinx ci
  docs/source/_static/.gitkeep
Labels: chore

#413 chore: use collapsible readme
  Makefile
  README.md
  examples/stable_diffusion/server.py
  requirements/dev.txt
  setup.py
Labels: chore

#425 chore: add conda-forge badge to the readme
  README.md
Labels: chore
