Repository mosecorg/mosec, pull requests merged in 2025-01, with the labels that each got.

#615 feat: bump axum to 0.8, enable 3.13 test
  .github/workflows/check.yml
  Cargo.lock
  Cargo.toml
  requirements/dev.txt
  requirements/mixin.txt
Labels: enhancement

#616 feat: adopt maturin
  .github/workflows/check.yml
  .github/workflows/nightly.yml
  .github/workflows/package.yml
  .github/workflows/page.yml
  Cargo.lock
  Cargo.toml
  MANIFEST.in
  Makefile
  mosec/__init__.py
  mosec/runtime.py
  pyproject.toml
  requirements/dev.txt
  setup.py
  tests/test_service.py
Labels: enhancement

#617 chore: fix release ci yml
  .github/workflows/package.yml
  build.envd
Labels: chore

#619 chore: add cargo deny to lint cargo dependencies
  .github/workflows/deny.yml
  deny.toml
Labels: chore

#620 chore: fix cargo deny
  .github/workflows/deny.yml
Labels: chore

#621 fix: dockerfile mosec bin path & cargo-deny trigger
  .github/workflows/deny.yml
  Dockerfile
  deny.toml
Labels: bug_fix

#622 chore: fix discord badge
  README.md
Labels: chore

#623 chore: add ubuntu arm to ci test
  .github/workflows/check.yml
Labels: chore

#624 feat: find out the installed mosec path
  .github/workflows/check.yml
  mosec/runtime.py
  mosec/utils.py
  mosec/utils/__init__.py
Labels: enhancement

#625 Fix bibtex
  README.md
Labels: bug_fix
